apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aia-backend
  namespace: paw
  labels:
    team: paw
  annotations:
    config.linkerd.io/proxy-memory-limit: "512Mi"
    config.linkerd.io/proxy-memory-request: "128Mi"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  webproxy: true
  ingresses:
    - "https://www.nav.no/aia-backend"
    - "https://www.intern.nav.no/aia-backend"
    - "https://aia-backend.intern.nav.no/aia-backend"
  envFrom:
    - configmap: loginservice-idporten
  env:
    - name: CORS_ALLOWED_ORIGINS
      value: www.nav.no
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: MELDEKORT_APP_NAME
      value: "meldekort-api"
    - name: PTO_PROXY_URL
      value: https://pto-proxy.intern.nav.no/proxy
    - name: UNLEASH_API_URL
      value: https://unleash.nais.io/api/
  resources:
    limits:
      cpu: "3"
      memory: 1536Mi
    requests:
      cpu: "100m"
      memory: 580Mi
  accessPolicy:
    inbound:
      rules:
        - application: veientilarbeid
    outbound:
      rules:
        - application: dp-innsyn
          namespace: teamdagpenger
        - application: meldekort-api
          namespace: meldekort
#  gcp:
#    sqlInstances:
#      - type: POSTGRES_14
#        databases:
#          - name: bakveientilarbeid
