apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: esyfo-proxy
  namespace: team-esyfo
  labels:
    team: team-esyfo
  annotations:
    config.linkerd.io/proxy-memory-limit: 512Mi
    config.linkerd.io/proxy-memory-request: 128Mi
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: /esyfo-proxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /esyfo-proxy/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 4
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
      level: Level4
  ingresses:
    - https://www.nav.no/esyfo-proxy
  resources:
    limits:
      cpu: "3"
      memory: 1536Mi
    requests:
      cpu: 100m
      memory: 580Mi
  accessPolicy:
    outbound:
      rules:
        - application: aktivitetskrav-backend
          namespace: team-esyfo
          cluster: prod-gcp
        - application: isdialogmote
          namespace: teamsykefravr
          cluster: prod-gcp
    external:
      - host: syfomotebehov.prod-fss-pub.nais.io
  env:
    - name: BASE_PATH
      value: /esyfo-proxy
    - name: CORS_ALLOWED_ORIGINS
      value: www.nav.no
    - name: CORS_ALLOWED_SCHEMES
      value: https
    - name: SSO_NAV_COOKIE
      value: sso-nav.no
    - name: AKTIVITETSKRAV_BACKEND_HOST
      value: https://aktivitetskrav-backend.intern.nav.no
    - name: AKTIVITETSKRAV_BACKEND_CLIENT_ID
      value: prod-gcp:team-esyfo:aktivitetskrav-backend
    - name: SYFOMOTEBEHOV_HOST
      value: https://syfomotebehov.prod-fss-pub.nais.io
    - name: SYFOMOTEBEHOV_CLIENT_ID
      value: prod-fss:team-esyfo:syfomotebehov
    - name: ISDIALOGMOTE_HOST
      value: http://isdialogmote.teamsykefravr
    - name: ISDIALOGMOTE_CLIENT_ID
      value: prod-gcp:teamsykefravr:isdialogmote
